---
 - hosts: localhost
   become: true
   tasks:

     - name: cloudmesh configuration
       become_user: rahul
       shell: |
          cm refresh on
          cm key add rraghata --source=$HOME/.ssh/id_rsa.pub
          cm default cloud=chameleon
          cm default user=rraghata

     - name: Continue cloudmesh configuration if key exists       
       become_user: rahul
       shell: |
          cm info

     - name: upload
       become_user: rahul
       shell: |
          cm key upload
          cm secgroup upload
          cm secgroup list

