---
 - hosts: localhost
   become: yes
   tasks:

     - name: install dependencies
       sudo: yes
       shell: |
         apt-get update
         apt-get upgrade
         apt-get dist-upgrade
         apt-get install python-setuptools
         apt-get install python-pip
         apt-get install python-dev
         apt-get install libncurses-dev
         apt-get install git
         easy_install readline
         pip install pycrypto
         apt-get install build-essential checkinstall
         apt-get install libreadline-gplv2-dev
         apt-get install libncursesw5-dev
         apt-get install libssl-dev
         apt-get install libsqlite3-dev
         apt-get install tk-dev
         apt-get install libgdbm-dev
         apt-get install libc6-dev
         apt-get install libbz2-dev
         cd $HOME
         wget --no-check-certificate https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz
         wget --no-check-certificate https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py
         wget --no-check-certificate https://bootstrap.pypa.io/get-pip.py
         tar xzf Python-2.7.10.tgz
         cd Python-2.7.10
         ./configure --prefix=/usr/local
         make && sudo make altinstall
         export PATH="/usr/local/bin:$PATH"
         cd $HOME
         /usr/local/bin/python2.7 ez_setup.py
         /usr/local/bin/python2.7 get-pip.py
         ln -sf /usr/local/bin/python2.7 /usr/local/bin/python
         ln -sf /usr/local/bin/pip /usr/bin/pip
         pip install -U pip
         virtualenv -p /usr/local/bin/python $HOME/ENV
