---
 - hosts: localhost
   become: true
   tasks:

     - name: define hadoop cluster
       become_user: rahul
       shell: |
          cm cluster define --count 3 --image CC-Ubuntu14.04
          cm hadoop define spark pig
          cm cluster avail
          cm hadoop avail

     - name: hadoop sync from github
       become_user: rahul
       shell: |
          cm hadoop sync

     - name: deploy hadoop cluster
       become_user: rahul
       shell: cm hadoop deploy
