---
 - hosts: localhost
   become: true
   tasks:

     - name: update/upgrade
       become: true
       apt: update-cache=yes upgrade=dist

     - name: install build_essentials
       sudo: yes
       apt: name={{item}} state=present update_cache=yes
       with_items:
          - python-setuptools
          - python-pip
          - expect
          - git
          - build-essential
          - libpam-umask
          - libssl-dev
          - libffi-dev
          - python-dev
          - libncurses-dev
          - libreadline-gplv2-dev
          - libncursesw5-dev
          - libsqlite3-dev
          - tk-dev
          - libgdbm-dev
          - libc6-dev
          - libbz2-dev

     - name: pip upgrade
       command: pip install --upgrade pip

     - name: git_config
       sudo: yes
       shell: |
          git config --global user.name "Rahul Raghatate"
          git config --global user.email rvraghatate10@gmail.com

     - name: install python-dependency packages
       sudo: yes
       action: pip name={{item}} state=present
       with_items:
          - pycrypto
          - virtualenv
          - virtualenvwrapper
          - cryptography
          - httplib2

     - name: Manually create the initial virtualenv
       command: virtualenv -p /usr/bin/python $HOME/ENV

     - name: start virtualenv
       sudo: true
       shell: source "$HOME/ENV/bin/activate"
       args:
         executable: /bin/bash

     - name: Check if cloudmesh directory already exists
       sudo: yes
       stat: path=/usr/local/bin/cm
       register: cloudmesh_flag

     - name: Install cloudmesh_client
       sudo: yes
       pip: name=cloudmesh_client state=latest
       when: cloudmesh_flag.stat.exists == false

     - name: cm reset
       command: cm reset
       when: cloudmesh_flag.stat.exists == true

     - name: Upgrade cloudmesh_client
       sudo: yes
       pip: name=cloudmesh_client state=absent
       when: cloudmesh_flag.stat.exists == true

     - name: install
       pip: name=cloudmesh_client state=latest
       when: cloudmesh_flag.stat.exists == true

     - name: ssh key_check
       sudo: yes
       stat: path=$HOME/.ssh/id_rsa.pub
       register: ssh_key_pub_flag

     - name:  create new ssh key if previously doesn't exist
       sudo: yes
       shell: ssh-keygen -b 2048 -t rsa -f $HOME/.ssh/id_rsa -q -N ""
       args:
          creates: $HOME/.ssh/rsa_pub
       when: ssh_key_pub_flag.stat.exists == false

     - name: cloudmesh configuration
       shell: |
          cm refresh on
          cm key add rraghata --source=$HOME/.ssh/id_rsa.pub
          cm default cloud=chameleon
          cm default user=rraghata

     - name: Continue cloudmesh configuration if key exists
       sudo: yes
       shell: |
          cm info

     - name: upload
       become: true
       become_user: rahul
       shell: |
          cm key upload
          cm secgroup upload
          cm secgroup list

     - name: define hadoop cluster
       become: yes
       become_user: rahul
       shell: |
          cm cluster define --count 3 --image CC-Ubuntu14.04
          cm hadoop define spark pig
          cm cluster avail
          cm hadoop avail

     - name: hadoop sync from github
       become: yes
       become_user: rahul
       shell: |
          cm hadoop sync

     - name: deploy hadoop cluster
       become: yes
       become_user: rahul
       shell: cm hadoop deploy
