---
- hosts: localhost
  become: true
  vars:
    local_packages:
          - python-setuptools
          - python-pip
          - expect
          - build-essential
          - libpam-umask
          - libssl-dev
          - libffi-dev
          - python-dev
          - libncurses-dev
          - libreadline-gplv2-dev
          - libncursesw5-dev
          - libsqlite3-dev
          - tk-dev
          - libgdbm-dev
          - libc6-dev
          - libbz2-dev

    local_pip_packages:
          - pycrypto
          - virtualenv
          - virtualenvwrapper
          - cryptography
          - httplib2

    local_home: "{{ lookup('env','HOME') }}"
    virtual_env_activate: "/ENV/bin/activate"
    cm_path: "/usr/local/bin/cm"
    rsa_pub_path: "/.ssh/id_rsa"
    key_path: "/.ssh/id_rsa.pub"
    python_path: "/usr/bin/python"
    local_user_name: "{{ lookup('env','USER') }}"
  
  tasks:
     - name: update/upgrade machine
       apt: update-cache=yes upgrade=dist

     - name: install build_essentials       
       apt: name={{item}} state=present update_cache=yes
       with_items: '{{ local_packages }}'

     - name: pip upgrade
       command: pip install --upgrade pip

     - name: install python-dependency packages
       become: yes
       action: pip name={{item}} state=present
       with_items: '{{ local_pip_packages }}'
