---
- hosts: master
  remote_user: true
  tasks:
    - name: change user to hadoop for running sign_detection program on spark
      sudo: yes
      shell: |
         su - hadoop -c "wget --no-check-certificate -O test1.jpg https://github.com/rahulraghatate/Spark-Hadoop-OpenCV/blob/master/code/data/test1.jpg"
         su - hadoop -c "wget --no-check-certificate -O classifier.xml https://raw.githubusercontent.com/markgaynor/stopsigns/master/stopsign_classifier.xml"
         su - hadoop -c "hdfs dfs -mkdir /opencv_workspace/input"
         su - hadoop -c "hdfs dfs -put test1.jpg /opencv_workspace/input/test1.jpg"
         su - hadoop -c "hdfs dfs -ls /opencv_workspace"
